In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# load data
data = load_iris()
X = data.data
y = data.target

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# create model
model = KNeighborsClassifier(n_neighbors=5) #n_neighbors is the value of k

# train
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

print(y_pred)

[0 1 1 0 1 0 2 2 1 1 2 1 2 0 0 2 0 1 0 1 0 0 1 2 2 0 0 2 2 2]


In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# test / evaluate
print("Actual values:   ", y_test)
print("Predicted values:", y_pred)



Actual values:    [0 1 1 0 1 0 2 2 1 1 2 1 2 0 0 2 0 1 0 1 0 0 1 2 2 0 0 1 2 2]
Predicted values: [0 1 1 0 1 0 2 2 1 1 2 1 2 0 0 2 0 1 0 1 0 0 1 2 2 0 0 2 2 2]


In [11]:

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9666666666666667

Confusion Matrix:
 [[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.90      0.95        10
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



#### 2

In [12]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris          # example multiclass dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# -------------------------------------------
# 1. Load dataset
# -------------------------------------------
data = load_iris()
X = data.data     # shape: (150, 4) — 4 features: sepal length/width, petal length/width
y = data.target   # 0, 1, or 2 — three flower species

# -------------------------------------------
# 2. Split into train and test
# -------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,      # 20% data for testing
    random_state=42
)

# -------------------------------------------
# 3. Scale features
# IMPORTANT: KNN uses distance, so features
# must be on the same scale. Without scaling,
# a feature with large values (e.g., 1000s)
# will dominate the distance calculation.
# -------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)   # learn mean/std from train, apply
X_test  = scaler.transform(X_test)        # apply SAME scaling to test

# -------------------------------------------
# 4. Build and train KNN model
# -------------------------------------------
k = 5   # number of neighbors to consider

model = KNeighborsClassifier(
    n_neighbors=k,          # K value
    metric="euclidean",     # distance metric
    weights="uniform"       # all neighbors vote equally
                            # use weights="distance" to give closer neighbors more vote
)
model.fit(X_train, y_train)

# -------------------------------------------
# 5. Predict
# -------------------------------------------
y_pred = model.predict(X_test)

# -------------------------------------------
# 6. Evaluate
# -------------------------------------------
print(f"K = {k}")
print("Accuracy        :", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification  :\n", classification_report(y_test, y_pred))

# -------------------------------------------
# 7. Finding the best K (Elbow method)
# -------------------------------------------
accuracies = []
k_range = range(1, 21)

for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    preds = knn.predict(X_test)
    accuracies.append(accuracy_score(y_test, preds))

best_k = k_range[accuracies.index(max(accuracies))]
print(f"\nBest K: {best_k} with accuracy: {max(accuracies):.4f}")


K = 5
Accuracy        : 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification  :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Best K: 1 with accuracy: 1.0000
